# Generated by Django 3.0.5 on 2020-07-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://image.flaticon.com/icons/svg/1344/1344788.svg', max_length=200),
        ),
    ]
